### ISSUE TITLE
Some little suggestions about the inputs

### ISSUE THREAD

**Issue by lecorguille** [workflow4metabolomics/profia#1]
Hi,

I think we should remove from every tools the [**library import method**](https://github.com/workflow4metabolomics/profia/blob/master/profia_config.xml#L21), it was just a trick but by the way it's no longer working within our production instance.

Can we also imagine to import some individual files like the beta version of the xcms tools are allowing [now](https://github.com/workflow4metabolomics/xcms/blob/dev/galaxy/xcms_xcmsset/abims_xcms_xcmsSet.xml#L67)?

**Comment by ethevenot** [comment]
Bonjour Gildas,
Bien sûr. Comme tu as vu, j'ai repris ton code pour l'import des fichiers et je t'en remercie (je pensais avoir pris la dernière version !). Je me calerai sur ta version au prochain commit (il faut de toute façon que nous fassions une modif rapidement du package proFIA pour pouvoir installer sur la version R 3.2.5 de la dev/prod ; actuellement R >= 3.3.0 seulement).
A bientôt,
Etienne.

**Comment by lecorguille** [comment]
Pas de soucis, c'est tout nouveau.
Ca fait quelques temps, que je me dis qu'il faut que mette ces fonctions d'import dans easyRlibrary (qui devrait changer de nom pour w4m_utils ou un truc comme ça) histoire de factoriser et harmoniser les outils.

(Mon conseil est de garder cette issue ouverte jusqu'à ce que tu push les modifications. C'est une manière de suivre les développements et de ne pas oublier une tache :P
Mais, pas de soucis)
